[auth]
site_url = "http://localhost:8089"
additional_redirect_urls = ["http://localhost:8089"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = false
enable_confirmations = false

[auth.external.github]
enabled = false

[auth.external.google]
enabled = false